### ISSUE TITLE
Increasing number of `id`s in Mutation query

### ISSUE THREAD

**Issue by ksmth** [relay-tools/react-router-relay#162] opened 2016-05-26 08:40 UTC
I have been trying to get to the bottom of https://github.com/facebook/relay/issues/1169 and I noticed something that at least appears odd to me. But I also might not know enough about how Relay works ...

Anyway, here it goes ... In the linked issue I complain about experiencing an increasing number of `id` fields in the generated query for a mutation. When stepping through the code, I noticed the following when observing the data flowing through https://github.com/facebook/relay/blob/551fe138b51146dac77b8551425c565b72f306d7/src/traversal/printRelayOSSQuery.js#L235:

<img width="1107" alt="screen shot 2016-05-26 at 10 31 43" src="https://cloud.githubusercontent.com/assets/1570868/15568716/a11a6ba0-232d-11e6-8d92-03254277f850.png">

As you can see there are 52 children, most of them have the same name associated with their `__route__`, which was generated by the aggregator. I don't really know where to go from here, any hints would be highly appreciated. :)

**Comment by taion** [comment] 2016-05-26 10:48
That's a dupe of an older Relay issue. Check the Relay issue tracker.

**Closed by taion** 2016-05-26 10:48 UTC

**Comment by ksmth** [comment] 2016-05-26 12:25
After a bit of digging I indeed found this, linking in case someone else comes here, too:
https://github.com/facebook/relay/issues/1098

Thanks @taion :)
