### ISSUE TITLE
Parameter binding on (root) queries broken in 0.7?

### ISSUE THREAD

**Issue by justinsb** [relay-tools/react-router-relay#70] opened 2015-11-02 16:14 UTC
Passing parameters to a top-level relay query (as in the first example from the README) seems to work on 0.6.2, but fail on 0.7.0.  On 0.7.0 no parameter value is passed to `widget`.  Downgrading to 0.6.2, the parameter is passed as expected.

e.g.
```
const WidgetQueries = {
  widget: () => Relay.QL`
    query {
      widget(widgetId: $widgetId) # `widgetId` receives a value from the route
    }
  `
}

const widgetRoute = (
  <Route
    path="widgets/:widgetId" component={Widget}
    queries={WidgetQueries}
  />
);
```

**Comment by taion** [comment] 2015-11-02 16:19
This is literally the only change between 0.6.2 and 0.7.0 though: https://github.com/relay-tools/react-router-relay/commit/7221ebf9cc37c3c4189a404b3d9cfb2a4a855ae1. Are you sure it's not some dependency thing?

**Comment by devknoll** [comment] 2015-11-04 03:39
Running into this too. Crazy hunch is that RR 1.0-rc4 reversed the order of `routes`, but haven't actually had a chance to look into it.

**Comment by devknoll** [comment] 2015-11-04 04:09
Running into this too. Seems related to react-relay@0.4.0 changes.

**Comment by taion** [comment] 2015-11-04 04:11
Okay I see it's most likely https://github.com/facebook/relay/commit/6cc8f96cdb7dcebebb38f30b7d64b08dfd83fb18 then.

**Comment by taion** [comment] 2015-11-04 04:13
Err scratch that, no it's not.

**Comment by taion** [comment] 2015-11-04 04:31
I'm puzzled - I use this pattern in my code and it works just fine.

**Comment by taion** [comment] 2015-11-04 04:41
Are either of you using `prepareParams`?

**Comment by devknoll** [comment] 2015-11-04 04:42
Nope.

**Comment by taion** [comment] 2015-11-04 04:54
I'm totally stumped then. I tried a couple of variations of using this pattern locally and they all seemed to work.

**Comment by taion** [comment] 2015-11-04 04:55
I've been meaning to set some time aside to add test coverage anyway - this is probably a good motivation. But I'd appreciate any help getting a repro for this, since I'm not sure how I'd reproduce in an automated way a bug that I can't reproduce manually.

**Comment by devknoll** [comment] 2015-11-04 05:05
> Okay I see it's most likely facebook/relay@6cc8f96 then.

This was my initial thought too... some quick sleuthing indicated that the routes/params were being correctly passed down by RRR, but the params themselves aren't being written out in the query on the Relay end.

**Comment by taion** [comment] 2015-11-04 05:12
That's not new to Relay v0.4.0 or RRR v0.7.0 though.

What version of babel-relay-plugin do you have?

**Comment by taion** [comment] 2015-11-04 05:15
A possible culprit is https://github.com/facebook/relay/commit/356529f40099c32bbbb4ae2b29e5e011f445a22e, if you haven't upgraded babel-relay-plugin to v0.3.0.

I see that Relay v0.4.0 was shipped without the peer dependency, though Relay on master now has it.

**Comment by devknoll** [comment] 2015-11-04 05:42
/facepalm

Updating to 0.3.0 fixes it.

**Comment by taion** [comment] 2015-11-04 05:45
And - it's something that automated testing probably wouldn't have caught (since I would have upgraded everything all at once), so I feel less guilty now for not having any tests. And it's good to see the peer dependency now listed under Relay.

@justinsb It's quite likely you're hitting the same problem - I'm going to close this issue under that assumption, but let me know if it's otherwise.

**Closed by taion** 2015-11-04 05:45 UTC
